'use client';

import { useState } from 'react';
import type { AnalysisMetrics } from '@/lib/api';
import {
  calculateDelta,
  getScoreColor,
  getScoreColorClass,
} from '@/lib/metrics';

interface MetricsComparisonProps {
  originalMetrics: AnalysisMetrics;
  optimizedMetrics: AnalysisMetrics;
  filename?: string;
  className?: string;
}

// Focus on the 4 key metrics (not including learning_score which is shown at top)
const KEY_METRICS = [
  { key: 'cognitive_load' as const, label: 'Cognitive Load', lowerIsBetter: true },
  { key: 'concept_flow' as const, label: 'Concept Flow', lowerIsBetter: false },
  { key: 'engagement' as const, label: 'Engagement', lowerIsBetter: false },
  { key: 'retention' as const, label: 'Retention', lowerIsBetter: false },
];

export function MetricsComparison({
  originalMetrics,
  optimizedMetrics,
  filename = 'curriculum',
  className = '',
}: MetricsComparisonProps) {
  const [showChanges, setShowChanges] = useState(false);

  const learningScoreDelta = calculateDelta(
    optimizedMetrics.learning_score,
    originalMetrics.learning_score,
    false
  );

  const getDetailedChanges = () => {
    const allMetrics = [
      { key: 'learning_score', label: 'Learning Score', lowerIsBetter: false },
      ...KEY_METRICS,
    ];

    const changes = allMetrics.map((metric) => {
      const original = originalMetrics[metric.key];
      const optimized = optimizedMetrics[metric.key];
      const delta = calculateDelta(optimized, original, metric.lowerIsBetter);
      return {
        metric: metric.label,
        key: metric.key,
        original: Math.round(original),
        optimized: Math.round(optimized),
        change: delta.displayDelta,
        improved: delta.isImprovement,
      };
    });

    return changes;
  };

  const getChangeDescription = (metricKey: string) => {
    // These would ideally come from the backend with specific content changes
    // For now, providing detailed descriptions based on metrics
    const descriptions: Record<string, string[]> = {
      cognitive_load: [
        'Split complex topics into smaller, digestible sections',
        'Added visual aids to reduce text-heavy explanations',
        'Introduced progressive complexity building',
        'Restructured content hierarchy for better mental models',
      ],
      engagement: [
        'Added interactive examples and thought-provoking questions',
        'Incorporated real-world case studies and applications',
        'Enhanced content with relatable scenarios',
        'Introduced practice exercises at key intervals',
      ],
      concept_flow: [
        'Improved transitions between related topics',
        'Added concept mapping and visual connections',
        'Restructured learning progression for logical flow',
        'Enhanced cross-referencing of related concepts',
      ],
      retention: [
        'Introduced spaced repetition of key concepts',
        'Added summary sections after major topics',
        'Incorporated retrieval practice opportunities',
        'Enhanced with mnemonic devices and memory aids',
      ],
    };

    return descriptions[metricKey] || ['Optimized content structure and delivery'];
  };

  const generateReport = () => {
    const changes = getDetailedChanges();
    const improvements = changes.filter((c) => c.improved);
    const timestamp = new Date().toLocaleString();

    const report = `
CURRICULUM OPTIMIZATION REPORT
=====================================
Document: ${filename}
Generated: ${timestamp}

SUMMARY
-------
Learning Score: ${changes[0].original} → ${changes[0].optimized} (${changes[0].change})
Improvements: ${improvements.length} metrics enhanced
Status: ✓ Optimization Complete

${improvements.length > 0 ? `
CHANGES APPLIED
---------------
${improvements
  .map((change) => {
    const descriptions = getChangeDescription(change.key);
    return `
${change.metric} (${change.original} → ${change.optimized})
${descriptions.map((d) => `  • ${d}`).join('\n')}`;
  })
  .join('\n')}` : ''}

FULL METRICS BREAKDOWN
----------------------
${changes
  .slice(1)
  .map(
    (c) =>
      `${c.metric}: ${c.original} → ${c.optimized} (${c.change})${c.improved ? ' ✓' : ''}`
  )
  .join('\n')}

---
Generated by Curriculearn Neural Optimization System
    `.trim();

    return report;
  };

  const handleDownload = () => {
    const report = generateReport();
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `optimization-report-${filename.replace(/\.[^/.]+$/, '')}-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };


  return (
    <div className={`space-y-8 ${className}`}>
      {/* Header with badge and actions */}
      <div className="flex items-center justify-between">
        <div className="font-mono text-[0.65rem] uppercase tracking-[0.24em] text-emerald-500/80">
          ✓ Optimization Complete
        </div>

        <div className="flex items-center gap-3">
          {/* View Changes Button */}
          <button
            onClick={() => setShowChanges(!showChanges)}
            className="font-mono text-[0.65rem] uppercase tracking-[0.16em] text-fg/50 transition-colors hover:text-accent"
          >
            {showChanges ? '− Hide' : '+ View'} Changes
          </button>

          {/* Download Button */}
          <button
            onClick={handleDownload}
            className="group flex items-center gap-2 rounded-sm border border-accent/30 bg-accent/10 px-4 py-2 font-mono text-[0.65rem] uppercase tracking-[0.16em] text-accent transition-all hover:border-accent/50 hover:bg-accent/15"
          >
            <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download Report
          </button>
        </div>
      </div>

      {/* Detailed Changes Report (collapsible) */}
      {showChanges && (
        <div className="animate-in fade-in slide-in-from-top-2 duration-300 rounded-lg border border-fg/10 bg-gradient-to-b from-bg to-[#0d0e11] p-6">
          {/* Header */}
          <div className="mb-6 border-b border-fg/10 pb-4">
            <div className="mb-2 font-mono text-[0.65rem] uppercase tracking-[0.24em] text-emerald-500/80">
              Optimization Report
            </div>
            <div className="font-mono text-[0.75rem] text-fg/60">
              {new Date().toLocaleDateString('en-US', {
                month: 'long',
                day: 'numeric',
                year: 'numeric',
                hour: '2-digit',
                minute: '2-digit'
              })}
            </div>
          </div>

          {/* Summary Stats */}
          <div className="mb-6 grid grid-cols-3 gap-4 rounded-sm border border-fg/10 bg-bg/50 p-4">
            <div>
              <div className="mb-1 font-mono text-[0.6rem] uppercase tracking-wider text-fg/40">
                Learning Score
              </div>
              <div className="font-mono text-lg font-bold text-emerald-500">
                {learningScoreDelta.displayDelta}
              </div>
            </div>
            <div>
              <div className="mb-1 font-mono text-[0.6rem] uppercase tracking-wider text-fg/40">
                Improvements
              </div>
              <div className="font-mono text-lg font-bold text-fg/90">
                {getDetailedChanges().filter(c => c.improved).length}/{getDetailedChanges().length}
              </div>
            </div>
            <div>
              <div className="mb-1 font-mono text-[0.6rem] uppercase tracking-wider text-fg/40">
                Status
              </div>
              <div className="font-mono text-[0.7rem] font-semibold text-emerald-500">
                ✓ Complete
              </div>
            </div>
          </div>

          {/* Detailed Changes */}
          <div className="space-y-6">
            <div className="font-mono text-[0.7rem] uppercase tracking-[0.2em] text-fg/55">
              Changes Applied
            </div>

            {getDetailedChanges()
              .filter(change => change.improved && change.key !== 'learning_score')
              .map((change, idx) => (
                <div key={idx} className="space-y-3 rounded-sm border border-fg/10 bg-bg/30 p-4">
                  {/* Metric header */}
                  <div className="flex items-center justify-between border-b border-fg/10 pb-2">
                    <div className="font-mono text-[0.75rem] font-semibold text-fg/90">
                      {change.metric}
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="font-mono text-[0.7rem] text-fg/50">
                        {change.original} → {change.optimized}
                      </span>
                      <span className="font-mono text-[0.7rem] font-semibold text-emerald-500">
                        {change.change}
                      </span>
                    </div>
                  </div>

                  {/* Change descriptions */}
                  <div className="space-y-2">
                    {getChangeDescription(change.key).map((description, descIdx) => (
                      <div key={descIdx} className="flex items-start gap-2">
                        <span className="mt-1 text-emerald-500/60">•</span>
                        <span className="font-mono text-[0.7rem] leading-relaxed text-fg/70">
                          {description}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              ))}

            {getDetailedChanges().filter(c => c.improved && c.key !== 'learning_score').length === 0 && (
              <div className="rounded-sm border border-fg/10 bg-bg/30 p-6 text-center">
                <div className="font-mono text-[0.7rem] text-fg/50">
                  General curriculum structure optimizations applied
                </div>
              </div>
            )}
          </div>
        </div>
      )}


      {/* Learning score comparison */}
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        {/* Original score */}
        <div className="rounded-lg border border-fg/10 bg-bg/50 p-6 backdrop-blur-sm">
          <div className="mb-2 font-mono text-xs uppercase tracking-wider text-fg/50">
            Original Curriculum
          </div>
          <div
            className={`text-4xl font-bold ${getScoreColorClass(originalMetrics.learning_score)}`}
          >
            {Math.round(originalMetrics.learning_score)}
          </div>
          <div className="mt-1 font-mono text-xs text-fg/40">Learning Score</div>
        </div>

        {/* Optimized score */}
        <div className="rounded-lg border border-emerald-500/20 bg-emerald-500/5 p-6 backdrop-blur-sm">
          <div className="mb-2 font-mono text-xs uppercase tracking-wider text-emerald-500/70">
            Optimized Curriculum
          </div>
          <div className="flex items-baseline gap-3">
            <div
              className={`text-4xl font-bold ${getScoreColorClass(optimizedMetrics.learning_score)}`}
            >
              {Math.round(optimizedMetrics.learning_score)}
            </div>
            <div className="text-xl font-semibold text-emerald-500">
              {learningScoreDelta.displayDelta}
            </div>
          </div>
          <div className="mt-1 font-mono text-xs text-fg/40">Learning Score</div>
        </div>
      </div>

      {/* Key metrics grid */}
      <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
        {KEY_METRICS.map((metric) => {
          const original = originalMetrics[metric.key];
          const optimized = optimizedMetrics[metric.key];
          const delta = calculateDelta(optimized, original, metric.lowerIsBetter);

          return (
            <div
              key={metric.key}
              className="group relative overflow-hidden rounded-lg border border-fg/10 bg-gradient-to-b from-bg to-[#0d0e11] p-6 transition-all duration-300 hover:border-fg/20 hover:shadow-[0_8px_30px_rgba(0,0,0,0.3)]"
            >
              <div className="relative z-10">
                {/* Label */}
                <div className="mb-5 font-mono text-[0.7rem] uppercase tracking-[0.2em] text-fg/50">
                  {metric.label}
                </div>

                {/* Original and Optimized side by side */}
                <div className="grid grid-cols-2 gap-4">
                  {/* Original */}
                  <div className="text-left">
                    <div className="mb-2 font-mono text-[0.6rem] uppercase tracking-wider text-fg/40">
                      Original
                    </div>
                    <div
                      className={`text-3xl font-bold ${getScoreColorClass(original)}`}
                      style={{
                        textShadow: `0 0 20px ${getScoreColor(original)}30`,
                      }}
                    >
                      {Math.round(original)}
                    </div>
                  </div>

                  {/* Optimized */}
                  <div className="text-right">
                    <div className="mb-2 font-mono text-[0.6rem] uppercase tracking-wider text-emerald-500/70">
                      Optimized
                    </div>
                    <div className="flex items-baseline justify-end gap-2">
                      <div
                        className={`text-3xl font-bold ${getScoreColorClass(optimized)}`}
                        style={{
                          textShadow: `0 0 20px ${getScoreColor(optimized)}30`,
                        }}
                      >
                        {Math.round(optimized)}
                      </div>
                      <div
                        className={`text-sm font-semibold ${
                          delta.isImprovement ? 'text-emerald-500' : 'text-red-500'
                        }`}
                      >
                        {delta.displayDelta}
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Hover glow effect */}
              <div
                className="pointer-events-none absolute inset-0 opacity-0 transition-opacity duration-500 group-hover:opacity-100"
                style={{
                  background: `radial-gradient(circle at 50% 0%, ${getScoreColor(optimized)}10 0%, transparent 70%)`,
                }}
              />
            </div>
          );
        })}
      </div>
    </div>
  );
}
